### ISSUE TITLE
About the hmac-sha1 key

### ISSUE THREAD

**Issue by faith0811** [twisteroidambassador/llsifclient#1]
Hi twisteroidambassador,

I have done some research about the sif client before. Like you said in readme, I found that the client would send a 40-length `X-Message-Code` in HTTP header. And I disassembled the `LibGame.so`, but I didn't find anything useful except the signature method `hmac-sha1`.

So, Did you find out how to get the `hmac-sha1` key? If so, could you give me some hints about how to get it, or what tools you're using.

I am excited that someone else tried to decrypt the client, and this is a really nice project, thank you for what you're doing.

Btw, the client does not send the signature when its first communication connects to the server. So I think might be the key does not contains in the code directly.

thanks,
niconiconi!!

**Comment by twisteroidambassador** [comment]
Hi,

If you've already found the function calculating HMAC, the rest is not that difficult. Just trace back to where the HMAC() function is being called and look at its arguments, one of them will be the HMAC key. They tried to be sneaky and did not use strcpy() for the key, but just read the code carefully and it should be fairly easy to figure out.

I used the free version of IDA which only works with x86 binaries, and looked at the x86 version of `LibGame.so`.

Good luck, and Nico Nico Nii~

**Comment by xfoxfu** [comment]
Sorry to disturb, but I have trouble in finding the HMAC function since I have little knowledge of Assemble.

Would you offer me some detailed information on how to find the function? I have successfully decompiled the `libGame.so` but I find it hard to intercept the codes even with `Pseudocode`.

And I would like to know what the key looks like.

If this comment make you unwell, just tell me and I will delete it.

**Comment by dev-techmoe** [comment]
Is the token of the hmacsha1 can be found in the Strings window of the IDA?

**Comment by xfoxfu** [comment]
@dev-techmoe I think it can't according to the readme and my own experience.

> It can not be found by simply running strings over the binary; that would be way too easy.

**Comment by xfoxfu** [comment]
rm to avoid the possible legal risk. but the content still apply.

**Comment by twisteroidambassador** [comment]
@coderfox You are looking at the right place. Are you familiar with how integers are stored in memory?

**Comment by faith0811** [comment]
Thank you all.
Resolved.

**Comment by chazeon** [comment]
Is the key for Japanese client a 11 byte long `bytearray`, that starts with byte `0x56` and ends with `0x62`? I tried to use this key to digest a response body I intercept from the HTTP request sent from the official client, it didn't match the `X-Message-Code` header within the same request. And is the request body, that is digested, should be the one line JSON object, without line breaks, boundaries, empty lines, and the `Content-Disposition` line?

**Comment by twisteroidambassador** [comment]
The length does sound correct, but the start byte seems wrong; did you make a typo?
The HMAC is indeed done on the one line JSON object only.

**Comment by chazeon** [comment]
So I guess I'm making some mistake but I'm not sure where. My disassemble code from position `1c1534`, where the sequence started to `1c1551` where the sequence ended looks like:
```
  1c1534:	c7 83 90 48 03 00 57 	mov    DWORD PTR [ebx+0x34890],0x56747957
  1c153b:	79 74 56 
  ...
  1c1551:	c6 83 9a 48 03 00 62 	mov    BYTE PTR [ebx+0x3489a],0x62
```
So I don't think `0x56` is a typo problem ... there should be something that I'm understanding wrongly.

**Comment by twisteroidambassador** [comment]
Ah, yes, "that" problem. Remember x86 is little-endian.

**Comment by chazeon** [comment]
Oh I get that, got a matching code finally... thank you for your patience!
